services:
  source:
    image: exilesprx/exercism-zig:source
    build:
      context: .docker
      args:
        VERSION: 0.13.0-dev.348+c564a16a0
      target: source

  zig:
    image: exilesprx/exercism-zig:latest
    build:
      cache_from:
        - exilesprx/exercism-zig:source
      context: .docker
      target: latest
