name: Docker image builds

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docker-compose.build.yml
      - .docker/**

env:
  COMPOSE_FILE: docker-compose.build.yml

jobs:
  lint-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        run: docker run --rm -i -v "$PWD"/hadolint.yml:/.config/hadolint.yaml hadolint/hadolint < .docker/Dockerfile

  build:
    needs: lint-docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: |
          docker compose build --pull zig
          docker compose push zig
