name: Feature builds

on:
  push:
    branches:
      - "feature/**"
    paths:
      - "docker-compose.build.yml"
      - ".docker/**"

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: |
          echo "Verify docker can build the images"
          docker compose -f docker-compose.build.yml build --pull source
          docker compose -f docker-compose.build.yml build --pull zig
