name: Tests
on:
  push:
    branches-ignore:
      - "main"

jobs:
  runs-on: ubuntu-latest
  container: exilesprx/exercism-zig:latest

  tests:
    steps:
      - uses: actions/checkout@v4

      - name: "Run tests"
        run: zig build test --summary all
